package com.neueda.leap.trading.order;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;import com.neueda.leap.trading.account.*;import com.neueda.leap.trading.cash.*;import com.neueda.leap.trading.client.CurrentClient;import com.neueda.leap.trading.instrument.*;import com.neueda.leap.trading.marketdata.*;import com.neueda.leap.trading.position.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;

@ExtendWith(org.mockito.junit.jupiter.MockitoExtension.class)
class OrderServiceTest{
 @Mock CurrentClient currentClient;@Mock AccountRepository accounts;@Mock InstrumentService instruments;@Mock MarketDataService marketData;@Mock CashBalanceRepository cash;@Mock PositionRepository positions;@Mock OrderRepository orders;@Mock OrderEventRepository events;@Mock OutboxEventRepository outbox;@InjectMocks OrderService service;
 UUID clientId=UUID.randomUUID(),accountId=UUID.randomUUID(),instrumentId=UUID.randomUUID();Account account;Instrument instrument;QuoteResponse quote;
 @BeforeEach void setup(){account=new Account();account.setAccountId(accountId);account.setClientId(clientId);instrument=new Instrument();instrument.setInstrumentId(instrumentId);instrument.setSymbol("MSFT");instrument.setTradable(true);quote=new QuoteResponse(instrumentId,"MSFT","USD",new BigDecimal("499"),new BigDecimal("500"),"TEST",Instant.now());}
 private void common(){when(currentClient.clientId()).thenReturn(clientId);when(accounts.findByAccountIdAndClientId(accountId,clientId)).thenReturn(Optional.of(account));when(instruments.findEntityBySymbol("MSFT")).thenReturn(instrument);when(marketData.getCurrentQuote("MSFT")).thenReturn(quote);}
 @Test void acceptsBuyWhenCashIsSufficient(){common();CashBalance b=CashBalance.open(accountId,"USD",Instant.now());b.setBalance(new BigDecimal("10000"));when(cash.find(accountId,"USD")).thenReturn(Optional.of(b));OrderResponse r=service.submit(new CreateOrderRequest(accountId,"MSFT","buy",new BigDecimal("2")));assertEquals("ACCEPTED",r.status());assertEquals("BUY",r.side());verify(orders).insert(any(Order.class));verify(events,times(2)).insert(any(OrderEvent.class));verify(outbox).insert(any(OutboxEvent.class));}
 @Test void rejectsBuyWithInsufficientCash(){common();CashBalance b=CashBalance.open(accountId,"USD",Instant.now());b.setBalance(new BigDecimal("100"));when(cash.find(accountId,"USD")).thenReturn(Optional.of(b));OrderRejectedException e=assertThrows(OrderRejectedException.class,()->service.submit(new CreateOrderRequest(accountId,"MSFT","BUY",BigDecimal.ONE)));assertEquals("Insufficient cash",e.getMessage());verifyNoInteractions(orders,outbox);}
 @Test void rejectsSellWithInsufficientHolding(){common();when(positions.find(accountId,instrumentId)).thenReturn(Optional.empty());OrderRejectedException e=assertThrows(OrderRejectedException.class,()->service.submit(new CreateOrderRequest(accountId,"MSFT","SELL",BigDecimal.ONE)));assertEquals("Insufficient holding",e.getMessage());verifyNoInteractions(orders,outbox);}
 @Test void rejectsNonTradableInstrument(){when(currentClient.clientId()).thenReturn(clientId);when(accounts.findByAccountIdAndClientId(accountId,clientId)).thenReturn(Optional.of(account));instrument.setTradable(false);when(instruments.findEntityBySymbol("MSFT")).thenReturn(instrument);assertThrows(OrderRejectedException.class,()->service.submit(new CreateOrderRequest(accountId,"MSFT","BUY",BigDecimal.ONE)));verifyNoInteractions(marketData,orders);}
 @Test void rejectsInvalidSide(){when(currentClient.clientId()).thenReturn(clientId);when(accounts.findByAccountIdAndClientId(accountId,clientId)).thenReturn(Optional.of(account));when(instruments.findEntityBySymbol("MSFT")).thenReturn(instrument);assertThrows(OrderRejectedException.class,()->service.submit(new CreateOrderRequest(accountId,"MSFT","HOLD",BigDecimal.ONE)));verifyNoInteractions(marketData,orders);}
}
