package com.neueda.leap.trading.identity;
import java.time.Instant; import java.util.*; import org.apache.ibatis.annotations.*;
/** MyBatis mapper for identities, roles, registration, and bootstrap. */
@Mapper public interface IdentityMapper {
 @Select("SELECT user_id userId,email,first_name firstName,last_name lastName,active,created_at createdAt,updated_at updatedAt FROM identity.users ORDER BY created_at,email") List<IdentityUserRow> users();
 @Select("SELECT user_id userId,email,first_name firstName,last_name lastName,active,created_at createdAt,updated_at updatedAt FROM identity.users WHERE user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler}") Optional<IdentityUserRow> user(UUID id);
 @Select("SELECT r.role_name FROM identity.user_roles ur JOIN identity.roles r ON r.role_id=ur.role_id WHERE ur.user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler} ORDER BY r.role_name") List<String> roles(UUID id);
 @Select("SELECT COUNT(*) FROM identity.users WHERE user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler}") int userCount(UUID id);
 @Select("SELECT COUNT(*) FROM identity.users WHERE email=#{email}") int emailCount(String email);
 @Insert("INSERT INTO identity.users(user_id,email,password_hash,first_name,last_name,active,created_at,updated_at) VALUES(#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler},#{email},#{hash},#{first},#{last},true,#{now},#{now})") int insertUser(@Param("id")UUID id,@Param("email")String email,@Param("hash")String hash,@Param("first")String first,@Param("last")String last,@Param("now")Instant now);
 @Update("UPDATE identity.users SET active=#{active},updated_at=CURRENT_TIMESTAMP WHERE user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler}") int setActive(@Param("id")UUID id,@Param("active")boolean active);
 @Delete("DELETE FROM identity.user_roles WHERE user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler}") int deleteRoles(UUID id);
 @Insert("INSERT INTO identity.user_roles(user_id,role_id) SELECT #{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler},role_id FROM identity.roles WHERE role_name=#{role}") int insertRole(@Param("id")UUID id,@Param("role")String role);
 @Insert("INSERT INTO identity.clients(client_id,email,password_hash,first_name,last_name,client_segment,active) VALUES(#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler},#{email},#{hash},#{first},#{last},#{segment},true)") int insertClient(@Param("id")UUID id,@Param("email")String email,@Param("hash")String hash,@Param("first")String first,@Param("last")String last,@Param("segment")String segment);
 @Insert("INSERT INTO trading.accounts(account_id,client_id,account_number,base_currency,status) VALUES(#{accountId,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler},#{clientId,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler},#{number},'USD','ACTIVE')") int insertAccount(@Param("accountId")UUID accountId,@Param("clientId")UUID clientId,@Param("number")String number);
 @Insert("INSERT INTO trading.cash_balances(account_id,currency,balance) VALUES(#{accountId,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler},'USD',0)") int insertInitialCash(UUID accountId);
 @Insert("INSERT INTO identity.users(user_id,email,password_hash,first_name,last_name,active) VALUES(#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler},#{email},#{hash},'Super','Admin',true)") int insertSuperAdmin(@Param("id")UUID id,@Param("email")String email,@Param("hash")String hash);
 @Select("SELECT COUNT(*) FROM identity.users u JOIN identity.user_roles ur ON ur.user_id=u.user_id JOIN identity.roles r ON r.role_id=ur.role_id WHERE u.active=true AND r.role_name='SUPER_ADMIN'") int activeSuperAdminCount();
 @Select("SELECT COUNT(*) FROM identity.user_roles ur JOIN identity.roles r ON r.role_id=ur.role_id WHERE ur.user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler} AND r.role_name='SUPER_ADMIN'") int isSuperAdmin(UUID id);
 @Update("UPDATE identity.users SET email=#{email},first_name=#{firstName},last_name=#{lastName},updated_at=CURRENT_TIMESTAMP WHERE user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler}") int updateUser(@Param("id")UUID id,@Param("email")String email,@Param("firstName")String firstName,@Param("lastName")String lastName);
 @Insert("INSERT INTO identity.user_profiles(user_id,job_title,department,phone,timezone,notes) VALUES(#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler},#{p.jobTitle},#{p.department},#{p.phone},#{p.timezone},#{p.notes}) ON CONFLICT(user_id) DO UPDATE SET job_title=EXCLUDED.job_title,department=EXCLUDED.department,phone=EXCLUDED.phone,timezone=EXCLUDED.timezone,notes=EXCLUDED.notes,updated_at=CURRENT_TIMESTAMP") int upsertProfile(@Param("id")UUID id,@Param("p")UpdateUserProfileRequest p);
 @Select("SELECT user_id,job_title,department,phone,timezone,notes,updated_at FROM identity.user_profiles WHERE user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler}") Optional<UserProfileResponse> profile(UUID id);
 @Select("SELECT c.capability_name FROM identity.user_roles ur JOIN identity.role_capabilities rc ON rc.role_id=ur.role_id JOIN identity.capabilities c ON c.capability_id=rc.capability_id WHERE ur.user_id=#{id,typeHandler=com.neueda.leap.trading.config.PostgresUuidTypeHandler} ORDER BY c.capability_name") List<String> capabilities(UUID id);
 @Select("SELECT capability_name FROM identity.capabilities ORDER BY capability_name") List<String> allCapabilities();
 @Select("SELECT role_id roleId,role_name roleName,description,system_role systemRole FROM identity.roles ORDER BY role_name") List<RoleRow> roleRows();
 @Select("SELECT c.capability_name FROM identity.role_capabilities rc JOIN identity.capabilities c ON c.capability_id=rc.capability_id WHERE rc.role_id=#{roleId} ORDER BY c.capability_name") List<String> roleCapabilities(long roleId);
 @Insert("INSERT INTO identity.roles(role_name,description,system_role) VALUES(#{roleName},#{description},false)") @Options(useGeneratedKeys=true,keyProperty="roleId") int insertRoleRow(RoleRow role);
 @Update("UPDATE identity.roles SET description=#{description} WHERE role_id=#{roleId}") int updateRoleRow(RoleRow role);
 @Delete("DELETE FROM identity.role_capabilities WHERE role_id=#{roleId}") int deleteRoleCapabilities(long roleId);
 @Insert("INSERT INTO identity.role_capabilities(role_id,capability_id) SELECT #{roleId},capability_id FROM identity.capabilities WHERE capability_name=#{capability}") int insertRoleCapability(@Param("roleId")long roleId,@Param("capability")String capability);
 @Select("SELECT COUNT(*) FROM identity.roles WHERE role_name=#{role}") int roleNameCount(String role);
}
