package com.neueda.leap.trading.identity;
import java.time.Instant; import java.util.*; import org.springframework.dao.DuplicateKeyException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class IdentityService {
 private final IdentityMapper mapper; private final PasswordEncoder passwords;
 public IdentityService(IdentityMapper mapper,PasswordEncoder passwords){this.mapper=mapper;this.passwords=passwords;}
 public List<UserResponse> users(){return mapper.users().stream().map(this::response).toList();}
 public UserResponse user(UUID id){return response(mapper.user(id).orElseThrow(()->new IllegalArgumentException("User not found")));}
 @Transactional public UserResponse createAdmin(CreateAdminUserRequest r){validateRoles(r.roles());UUID id=UUID.randomUUID();Instant now=Instant.now();mapper.insertUser(id,r.email().toLowerCase(),passwords.encode(r.password()),r.firstName(),r.lastName(),now);replaceRoles(id,r.roles());return user(id);}
 @Transactional public UserResponse setActive(UUID id,boolean active){requireUser(id);if(!active&&mapper.isSuperAdmin(id)>0&&mapper.activeSuperAdminCount()<=1)throw new IllegalArgumentException("The last active Super Admin cannot be disabled");mapper.setActive(id,active);return user(id);}
 @Transactional public UserResponse replaceRoles(UUID id,List<String> roles){requireUser(id);validateRoles(roles);mapper.deleteRoles(id);for(String role:roles)if(mapper.insertRole(id,role)!=1)throw new IllegalArgumentException("Role not found: "+role);return user(id);}
 @Transactional public UserResponse updateProfile(UUID id,UpdateUserProfileRequest r){requireUser(id);mapper.updateUser(id,r.email().toLowerCase(),r.firstName(),r.lastName());mapper.upsertProfile(id,r);return user(id);}
 public UserProfileResponse profile(UUID id){requireUser(id);return mapper.profile(id).orElse(new UserProfileResponse(id,null,null,null,null,null,null));}
 @Transactional public ClientRegistrationResponse registerClient(ClientRegistrationRequest r){UUID clientId=UUID.randomUUID(),accountId=UUID.randomUUID();String email=r.email().toLowerCase(),number="ACC-"+accountId.toString().substring(0,8).toUpperCase();try{mapper.insertClient(clientId,email,passwords.encode(r.password()),r.firstName(),r.lastName(),"RETAIL");mapper.insertAccount(accountId,clientId,number);mapper.insertInitialCash(accountId);}catch(DuplicateKeyException e){throw new IllegalArgumentException("Email is already registered");}return new ClientRegistrationResponse(clientId,accountId,number,email);}
 private UserResponse response(IdentityUserRow u){return new UserResponse(u.getUserId(),u.getEmail(),u.getFirstName(),u.getLastName(),u.isActive(),mapper.roles(u.getUserId()),u.getCreatedAt(),u.getUpdatedAt());}
 public List<ClientAdminResponse> clients(){return mapper.clients();}
 public ClientAdminResponse client(UUID id){return mapper.client(id).orElseThrow(()->new IllegalArgumentException("Client not found"));}
 @Transactional public ClientAdminResponse updateClient(UUID id,UpdateClientRequest request){client(id);if(mapper.clientSegments().stream().noneMatch(s->s.segmentCode().equals(request.clientSegment())))throw new IllegalArgumentException("Unknown or inactive client segment");mapper.updateClient(id,request);return client(id);}
 public List<ClientSegmentResponse> clientSegments(){return mapper.clientSegments();}
 public List<String> capabilities(UUID id){requireUser(id);return mapper.capabilities(id);}
 public List<String> allCapabilities(){return mapper.allCapabilities();}
 public List<RoleResponse> roleDefinitions(){return mapper.roleRows().stream().map(r->new RoleResponse(r.getRoleId(),r.getRoleName(),r.getDescription(),r.isSystemRole(),mapper.roleCapabilities(r.getRoleId()))).toList();}
 @Transactional public RoleResponse createRole(CreateRoleRequest request){if(mapper.roleNameCount(request.roleName())>0)throw new IllegalArgumentException("Role already exists");RoleRow row=new RoleRow();row.setRoleName(request.roleName().trim().toUpperCase());row.setDescription(request.description());mapper.insertRoleRow(row);replaceRoleCapabilities(row.getRoleId(),request.capabilities());return roleDefinitions().stream().filter(r->r.roleId()==row.getRoleId()).findFirst().orElseThrow();}
 @Transactional public RoleResponse updateRole(long roleId,CreateRoleRequest request){RoleRow row=mapper.roleRows().stream().filter(r->r.getRoleId()==roleId).findFirst().orElseThrow(()->new IllegalArgumentException("Role not found"));row.setDescription(request.description());mapper.updateRoleRow(row);replaceRoleCapabilities(roleId,request.capabilities());return roleDefinitions().stream().filter(r->r.roleId()==roleId).findFirst().orElseThrow();}
 private void replaceRoleCapabilities(long roleId,List<String> capabilities){List<String> requested=capabilities==null?List.of():capabilities;RoleRow row=mapper.roleRows().stream().filter(r->r.getRoleId()==roleId).findFirst().orElseThrow();if(row.isSystemRole()&&(!requested.contains("USER_MANAGEMENT")||!requested.contains("ROLE_MANAGEMENT")))throw new IllegalArgumentException("System Super Admin must retain USER_MANAGEMENT and ROLE_MANAGEMENT");mapper.deleteRoleCapabilities(roleId);for(String capability:requested)if(mapper.insertRoleCapability(roleId,capability)!=1)throw new IllegalArgumentException("Unknown capability: "+capability);}
 private void validateRoles(List<String> roles){if(roles==null||roles.isEmpty())throw new IllegalArgumentException("Administrative user requires at least one role");if(roles.stream().anyMatch(r->mapper.roleNameCount(r)==0))throw new IllegalArgumentException("Unknown administrative role");}
 private void requireUser(UUID id){if(mapper.userCount(id)==0)throw new IllegalArgumentException("User not found");}
}