package com.neueda.leap.trading.execution;

import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;import com.neueda.leap.trading.cash.*;import com.neueda.leap.trading.marketdata.*;import com.neueda.leap.trading.order.*;import com.neueda.leap.trading.position.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;

@ExtendWith(org.mockito.junit.jupiter.MockitoExtension.class)
class OrderExecutionServiceTest{
 @Mock OrderRepository orders;@Mock FillRepository fills;@Mock MarketDataService marketData;@Mock PricingDecisionRepository pricing;@Mock CashBalanceRepository cash;@Mock CashTransactionRepository cashTx;@Mock PositionRepository positions;@Mock OrderEventRepository events;@Mock OrderStatusPublisher statusPublisher;@InjectMocks OrderExecutionService service;
 UUID orderId=UUID.randomUUID(),accountId=UUID.randomUUID(),instrumentId=UUID.randomUUID();
 private Order accepted(String side){Order o=Order.accepted(accountId,instrumentId,side,new BigDecimal("2"),Instant.now());o.setOrderId(orderId);return o;}
 @Test void executesAcceptedBuyAndPublishesFilledStatus(){Order o=accepted("BUY");when(orders.findById(orderId)).thenReturn(Optional.of(o));when(fills.existsByOrderId(orderId)).thenReturn(false);QuoteResponse q=new QuoteResponse(instrumentId,"MSFT","USD",new BigDecimal("499"),new BigDecimal("500"),"TEST",Instant.now());when(marketData.getCurrentQuoteByInstrumentId(instrumentId)).thenReturn(q);CashBalance b=CashBalance.open(accountId,"USD",Instant.now());b.setBalance(new BigDecimal("5000"));when(cash.find(accountId,"USD")).thenReturn(Optional.of(b));when(cash.update(b)).thenReturn(1);when(positions.find(accountId,instrumentId)).thenReturn(Optional.empty());when(orders.update(o)).thenReturn(1);service.execute(orderId);assertEquals("FILLED",o.getStatus());assertEquals(new BigDecimal("4000"),b.getBalance());verify(pricing).insert(any());verify(cashTx).insert(any());verify(positions).insert(any(Position.class));verify(fills).insert(any());verify(events,times(2)).insert(any());verify(statusPublisher).publish(argThat(m->m.orderId().equals(orderId)&&m.status().equals("FILLED")&&m.executionPrice().compareTo(new BigDecimal("500"))==0));}
 @Test void ignoresAlreadyFilledOrder(){Order o=accepted("BUY");o.markFilled(Instant.now());when(orders.findById(orderId)).thenReturn(Optional.of(o));service.execute(orderId);verifyNoInteractions(marketData,pricing,cash,cashTx,positions,events,statusPublisher);}
 @Test void ignoresOrderThatAlreadyHasFill(){Order o=accepted("BUY");when(orders.findById(orderId)).thenReturn(Optional.of(o));when(fills.existsByOrderId(orderId)).thenReturn(true);service.execute(orderId);verifyNoInteractions(marketData,pricing,cash,cashTx,positions,events,statusPublisher);}
 @Test void ignoresOrderNotAccepted(){Order o=accepted("BUY");o.setStatus("REJECTED");when(orders.findById(orderId)).thenReturn(Optional.of(o));when(fills.existsByOrderId(orderId)).thenReturn(false);service.execute(orderId);verifyNoInteractions(marketData,pricing,cash,cashTx,positions,events,statusPublisher);}
}
